name: Android CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/android.yml
      - android/**
  pull_request:
    paths:
      - .github/workflows/android.yml
      - android/**

jobs:
  build_signed_release_apk:
    name: Build and Sign App Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build with Gradle
        id: gradle_build_release
        run: ./android/gradlew assembleRelease -p android

      - name: Sign APK
        id: sign_apk_release
        uses: noriban/sign-android-release@v5
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed release apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ${{ steps.sign_apk_release.outputs.signedReleaseFile }}
          
  send_release_apk:
    name: Send Release APK
    runs-on: ubuntu-latest
    needs: build_signed_release_apk
    env:
         APP_NAME: "Tool-Telegram"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Download signed release apk
        uses: actions/download-artifact@v4
        with:
          name: app-release-signed
          
      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "message=$commit_message" >> $GITHUB_OUTPUT
          
      - name: Rename file 
        run: mv app-release-unsigned-signed.apk $APP_NAME.apk

      - name: Delete file 
        run: rm -f app-release-unsigned-signed.apk

      - name: Send APK to Release Channel Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: -1002230892820
          token: ${{ secrets.TELEGRAM_SIMPLE_BOT_TOKEN }}
          format: markdown
          document: $APP_NAME.apk
          disable_web_page_preview: false
          message: |
            *${{ github.actor }}* committed to [${{ github.repository }}](https://github.com/${{ github.repository }})

            Branch: *${{ github.head_ref }}*
            Commit message: `${{ steps.get_commit_msg.outputs.message }}`